<?php
/**
 * SendEmailConflictsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Mobile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mobile API
 *
 * ConnectWise Mobile API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Mobile;

use \Spinen\ConnectWise\Clients\Mobile\Configuration;
use \Spinen\ConnectWise\Clients\Mobile\ApiClient;
use \Spinen\ConnectWise\Clients\Mobile\ApiException;
use \Spinen\ConnectWise\Clients\Mobile\ObjectSerializer;

/**
 * SendEmailConflictsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Mobile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SendEmailConflictsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for mobileEmailsConflictPost
     *
     * .
     *
     */
    public function testMobileEmailsConflictPost()
    {

    }

}
